//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRez
    {
        public int RezId { get; set; }
        public int KId { get; set; }
        public int OtelId { get; set; }
        public int OdaId { get; set; }
        public System.DateTime RezTarih { get; set; }
        public Nullable<short> RezGün { get; set; }
    
        public virtual TblKullanici TblKullanici { get; set; }
        public virtual TblOda TblOda { get; set; }
        public virtual TblOtel TblOtel { get; set; }
    }
}
