//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYönetici
    {
        public int YId { get; set; }
        public string YAd { get; set; }
        public string YSoyad { get; set; }
        public string YTcNo { get; set; }
        public string YSifre { get; set; }
        public Nullable<int> OtelId { get; set; }
    
        public virtual TblOtel TblOtel { get; set; }
    }
}
